[phases.setup]
nixPkgs = ['python311', 'postgresql_16']

[phases.install]
cmds = [
    'python3.11 -m venv /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install --upgrade pip setuptools wheel',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'gunicorn app_production:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
